// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0Oo0en3xCvFk8QQL0c8Xb7mQ8qGPmvL8',
    appId: '1:119815104954:web:76a4d6c880875d5471d583',
    messagingSenderId: '119815104954',
    projectId: 'oshiwambo-translator-3f37d',
    authDomain: 'oshiwambo-translator-3f37d.firebaseapp.com',
    storageBucket: 'oshiwambo-translator-3f37d.firebasestorage.app',
    measurementId: 'G-ZWRGMEH3HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSITs6CVPaA-BO5drHfKjDz7x6mFKIdb4',
    appId: '1:119815104954:android:89504707e1c668d871d583',
    messagingSenderId: '119815104954',
    projectId: 'oshiwambo-translator-3f37d',
    storageBucket: 'oshiwambo-translator-3f37d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK_cJRTcIdGqIUOfIfBQPNCZilWJlJimY',
    appId: '1:119815104954:ios:a4958fa8f2e4e80871d583',
    messagingSenderId: '119815104954',
    projectId: 'oshiwambo-translator-3f37d',
    storageBucket: 'oshiwambo-translator-3f37d.firebasestorage.app',
    iosClientId: '119815104954-0bm7e77aqpibs1ggtblk7s4jj36o4v7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.oshiwamboTranslator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK_cJRTcIdGqIUOfIfBQPNCZilWJlJimY',
    appId: '1:119815104954:ios:a4958fa8f2e4e80871d583',
    messagingSenderId: '119815104954',
    projectId: 'oshiwambo-translator-3f37d',
    storageBucket: 'oshiwambo-translator-3f37d.firebasestorage.app',
    iosClientId: '119815104954-0bm7e77aqpibs1ggtblk7s4jj36o4v7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.oshiwamboTranslator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0Oo0en3xCvFk8QQL0c8Xb7mQ8qGPmvL8',
    appId: '1:119815104954:web:cc38de8ac10ccd5f71d583',
    messagingSenderId: '119815104954',
    projectId: 'oshiwambo-translator-3f37d',
    authDomain: 'oshiwambo-translator-3f37d.firebaseapp.com',
    storageBucket: 'oshiwambo-translator-3f37d.firebasestorage.app',
    measurementId: 'G-C424C8GNY8',
  );
}
